# Generated by Django 3.2.3 on 2021-06-06 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_message_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='listing',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=False),
        ),
    ]
