# Generated by Django 3.2.3 on 2021-06-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210606_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
