# Generated by Django 3.2.3 on 2021-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210607_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
