# Generated by Django 3.2.3 on 2021-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_oxygen_bed', models.IntegerField(default=0)),
                ('vaccant_oxygen_bed', models.IntegerField(default=0)),
                ('total_ICU_bed', models.IntegerField(default=0)),
                ('vaccant_ICU_bed', models.IntegerField(default=0)),
                ('total_covid_bed', models.IntegerField(default=0)),
                ('vaccant_covid_bed', models.IntegerField(default=0)),
                ('total_ventilator_bed', models.IntegerField(default=0)),
                ('vaccant_ventilator_bed', models.IntegerField(default=0)),
            ],
        ),
    ]
