# Generated by Django 3.2.3 on 2021-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='total_covid_bed',
            new_name='total_bed',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='vaccant_covid_bed',
            new_name='total_normal_bed',
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_vaccant_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='vaccant_normal_bed',
            field=models.IntegerField(default=0),
        ),
    ]
