# Generated by Django 3.2.3 on 2021-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210603_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='occupied_ICU_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='occupied_normal_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='occupied_oxygen_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='occupied_ventilator_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_occupied_bed',
            field=models.IntegerField(default=0),
        ),
    ]
