# Generated by Django 3.2.3 on 2021-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210603_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Phone_No',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
