# Generated by Django 3.2.3 on 2021-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_hospital_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Phone_No',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
